import { StyleSheet } from "react-native";


const styles = StyleSheet.create({
    Heading: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      width: 430,
      height: 150,
      paddingLeft: 26,
      paddingRight: 25,
      paddingTop: 10,
      paddingBottom: 17,
      boxSizing: "border-box",
      backgroundColor: "rgba(14,184,184,1)",
    },
    Group712: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      width: "100%",
      height: "100%",
      boxSizing: "border-box",
    },
    Group449: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      boxSizing: "border-box",
    },
    IonMenu: {
      width: 20,
      height: 20,
      top:30,
    },
    LogoAndName: {
      display: "flex",
      flexDirection: "row",
      alignItems: 'center',
      height: "100%",
      top: 30,
      left: 100,
      boxSizing: "border-box",
    },
    Logo: {
      width: 20.19,
      height: 20.19,
      right: 5
    },
    Pharmafetch: {
      color: "rgba(255,255,255,1)",
      fontSize: 13.18,
      lineHeight: 13.18,
      fontFamily: "Gotham Black, sans-serif",
      fontWeight: 'bold',
    },
    Ellipse1: {
      width: 30,
      height: 30,
      left: 190,
      top:30,
      borderRadius: 15,
      backgroundColor: "rgba(217,217,217,1)",
    },
    SearchBar: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      height: 40,
      width: 345,
      bottom: 10,
      paddingLeft: 23,
      paddingRight: 114,
      paddingTop: 13,
      paddingBottom: 14,
      borderRadius: 39,
      boxSizing: "border-box",
      backgroundColor: "rgba(255,255,255,1)",
    },
    IconSearch: {
      width: 20,
      height: 20,
    },
    SearchForPharmaciesM: {
      color: "rgba(0,0,0,0.5)",
      fontSize: 11,
      lineHeight: 11,
      fontFamily: "Gotham, sans-serif",
      left: 15,
    },

  //SERVICE CHOICES STYLES

    ServiceChoices: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      width: 430,
      height: 376,
      paddingLeft: 25,
      paddingRight: 26,
      paddingTop: 40,
      paddingBottom: 31,
      boxSizing: "border-box",
      backgroundColor: "rgba(14, 102, 184, 0.1)",
    },
    Container1: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      width: 100,
      boxSizing: "border-box",
    },
    DeliveryBox: {
      position: "relative",
      display: "flex",
      justifyContent: "center",
      alignItems: "flex-start",
      width: 164,
      height: 166,
      marginRight: 25,
      borderRadius: 10,
      boxSizing: "border-box",
      backgroundColor: "rgba(255, 255, 255, 1)",
    },
    DeliveryDescription: {
      position: "absolute",
      top: 124,
      display: "flex",
      flexDirection: "column",
      width: 149.56,
      height: 25,
      boxSizing: "border-box",
    },
    MedicineDelivery: {
      color: "rgba(0,0,0,1)",
      fontSize: 13.18,
      left: 20,
      lineHeight: 13.18,
      fontFamily: "Gotham, sans-serif",
      fontWeight: 'bold',
    },
    GetYourMedicinesOnYo: {
      color: "rgba(0,0,0,1)",
      left: 20,
      top: 4,
      fontSize: 8,
      lineHeight: 8,
      fontFamily: "Gotham, sans-serif",
    },
    PictureHere: {
        //CHANGE HERE FOR PICTURES
      position: "absolute",
      top: 53,
      left: 70,
      color: "rgba(0,0,0,1)",
      fontSize: 12,
      lineHeight: 12,
      fontFamily: "Gotham, sans-serif",
    },
    PickUpBox: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-end",
      width: 164,
      height: 166,
      right: 15,
      paddingLeft: 8,
      paddingRight: 28,
      paddingTop: 53,
      paddingBottom: 17,
      borderRadius: 10,
      boxSizing: "border-box",
      backgroundColor: "rgba(255,255,255,1)",
    },
    PictureHere1: {
    //CHANGE HERE FOR PICTURES
      position: "absolute",
      color: "rgba(0,0,0,1)",
      top:55,
      right: 20,
      fontSize: 12,
      lineHeight: 12,
      fontFamily: "Gotham, sans-serif",
    },
    Group443: {
      position: "absolute",
      top: 124,
      display: "flex",
      flexDirection: "column",
      width: 120,
      boxSizing: "border-box",
    },
    PickUp: {
      color: "rgba(0,0,0,1)",
      right: 25,
      fontSize: 13.18,
      lineHeight: 13.18,
      fontFamily: "Gotham, sans-serif",
      fontWeight: 'bold',
    },
    AlreadyOutsidePickIt: {
      color: "rgba(0,0,0,1)",
      fontSize: 8,
      top: 4,
      right: 25,
      lineHeight: 8,
      fontFamily: "Gotham, sans-serif",
    },
    Container2: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-evenly",
      width: 300,
      height: 100,
      boxSizing: "border-box",
    },
    PrescriptionBox: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      top: 25,
      width: 337,
      height: 115,
      paddingLeft: 16,
      paddingRight: 26,
      paddingTop: 34,
      paddingBottom: 35,
      borderRadius: 10,
      boxSizing: "border-box",
      backgroundColor: "rgba(255,255,255,1)",
    },
    Group6: {
      display: "flex",
      flexDirection: "column",
      height: 50,
      boxSizing: "border-box",
    },
    ValidatePrescription: {
      color: "rgba(0,0,0,1)",
      fontSize: 13.18,
      lineHeight: 13.18,
      fontFamily: "Gotham, sans-serif",
      fontWeight: 'bold',
    },
    GetYourDoctorSPrescr: {
      width: 159,
      top: 8,
      color: "rgba(0,0,0,1)",
      fontSize: 8,
      lineHeight: 8,
      fontFamily: "Gotham, sans-serif",
    },
    PictureHere2: {
      color: "rgba(0,0,0,1)",
      fontSize: 12,
      lineHeight: 12,
      fontFamily: "Gotham, sans-serif",
      fontWeight: 'bold',
    },
});

export default styles;